apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: "a3ViZW5ld3M="
  POSTGRES_PASSWORD: "cGcjMTIz"
  POSTGRES_DB: "a3ViZW5ld3M="
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_HOST: "cG9zdGdyZXNxbA=="
  DB_USERNAME: "a3ViZW5ld3M="
  DB_PASSWORD: "cGcjMTIz"
  DB_DATABASE: "a3ViZW5ld3M="
