apiVersion: v1
kind: Service
metadata:
  name: kubenews-service
  namespace: kubenews
spec:
  type: ClusterIP
  selector:
    app: kubenews
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
