apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubenews

resources:
- namespace.yaml
- secret-db.yaml
- Frontend/deployment-app.yaml
- Frontend/service-app.yaml
- ingress.yaml

images:
- name: 667516053160.dkr.ecr.us-east-2.amazonaws.com/kube-backend-repo
  newName: 667516053160.dkr.ecr.us-east-2.amazonaws.com/kube-backend-repo
  newTag: 2cf40e68a00ec33142211266d4be6750d28cfc0f
