apiVersion: v1
kind: Secret
metadata:
  name: kubenews-db
  namespace: kubenews
type: Opaque
stringData:
  DB_HOST: "kube-news-postgres.cfswqo42c9lb.us-east-2.rds.amazonaws.com" # terraform output rds_endpoint
  DB_PORT: "5432"
  DB_DATABASE: "kubedevnews"
  DB_USERNAME: "kubedevnews"
  DB_PASSWORD: "(VJ7fbVmW5$FLOrDq!7F26>O)dp!"
  DB_SSL_REQUIRE: "true"
