apiVersion: v1
kind: Secret
metadata:
  name: kubenews-db
  namespace: kubenews
type: Opaque
stringData:
  DB_HOST: kube-news-postgres.cfswqo42c9lb.us-east-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_DATABASE: "kubedevnews"
  DB_USERNAME: "kubedevnews"
  DB_PASSWORD: "Pg#123"
  DB_SSL_REQUIRE: "true"
