name: Application Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  ECR_REPOSITORY: kube-backend-repo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-update-kustomize:
    name: Build & Push Image + Update Kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -f kube-news-barbosadevops/APP/frontend/src/Dockerfile \
            -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            kube-news-barbosadevops//APP/frontend

          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Update kustomization image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd kubernetes
          kustomize edit set image $REGISTRY/$ECR_REPOSITORY=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add kustomization.yaml
          git commit -m "[BOT] Updating image to $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" || echo "No changes to commit"
          git push
